telegram_token: "7254895097:AAFLQ2hMPHoQFXBLPTG1k0S8ItcLfUciw8M"
openai_api_key: "sk-proj-kwGLV29qclIVBN7nTeiuT3BlbkFJaAfILGZoXqykk9BxE8YT"
openai_api_base: null  
allowed_telegram_usernames: []  
new_dialog_timeout: 1000  
return_n_generated_images: 1
n_chat_modes_per_page: 5
image_size: "512x512" 
enable_message_streaming: true  

# prices
chatgpt_price_per_1000_tokens: 0.002
gpt_price_per_1000_tokens: 0.02
whisper_price_per_1_min: 0.006
